server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bank
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
      host: smtp.gmail.com
      password: oxcxpkxpbzaltkkh
      port: 587
      properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true
      username: aquibnawaz78692@gmail.com
     
logging:
  level:
    org.zalando.logbook: TRACE
    