server:
  port: 8081
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bank
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    org.zalando.logbook: TRACE